title: pres-docs
description: Public repository for the Preservation and Collections Processing department at NYPL
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://nypl.github.io
baseurl: /pres-docs

aux_links:
  Home: https://nypl.github.io/pres-docs

nav_external_links:
  - title: Archival Processing
    url: https://nypl.github.io/archival-processing
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: ArchivesSpace
    url: https://nypl.github.io/archival-processing/aspace/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# Callouts
callouts:
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: purple
  alert:
    title: Alert
    color: red

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

# Footer
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "See this page on GitHub."
gh_edit_repository: "https://github.com/NYPL/pres-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately